### ISSUE TITLE
Error in "listStoredQueries" test

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/ets-wfs20#145]
The `listStoredQueries` test fails if it does not find a `wfs:ReturnFeatureType` element in the response:

``` 
Message: cvc-complex-type.2.4.b: The content of element 'wfs:StoredQuery' is not complete. One of '{"http://www.opengis.net/wfs/2.0":Title, "http://www.opengis.net/wfs/2.0":ReturnFeatureType}' is expected.
``` 

However, `wfs:ReturnFeatureType` is optional in the WFS XML schema at http://schemas.opengis.net/wfs/2.0/wfs.xsd. 

This has been introduced with WFS 2.0.2. But since the WFS 2.0.2 XML schema replaces the previous one, I would expect this test not to fail when `wfs:ReturnFeatureType` is not present.

**Comment by dstenger** [comment]
Thank you for reporting this.

However, WFS 2.0 test suite tests both versions (2.0.0 and 2.0.2). So, the old schema is still valid for services which state in the capabilities document that they are version 2.0.0.

Nevertheless, the test should be adjusted for WFS 2.0.2 services.

**Comment by lgoltz** [comment]
> However, WFS 2.0 test suite tests both versions (2.0.0 and 2.0.2). So, the old schema is still valid for services which state in the capabilities document that they are version 2.0.0.

As far as I understand the new schema version (with version="2.0.2") replaces the old one. The old schema is not longer available from http://schemas.opengis.net/wfs/ (or at least not directly, it is content of the archives).
Therefor I think we should remove the old schema from the ets. But I'm wondering about the version to use, since 2.0.2 the version must be valid against a pattern:

```
<xsd:simpleType name="VersionStringType">
  <xsd:restriction base="xsd:string">
  <xsd:pattern value="2\.0\.\d+"/>
</xsd:restriction></xsd:simpleType>
```

This makes the version 2.0.16 a valid version in requests (which are not validated by the ets) as well as TransactionResponse. 
To make it more complicated: In both specifications (2.0.0 and 2.0.2) the version of TransactionResponse is `version : CharacterString = "2.0. 0" {frozen}` in Figure 31 - Transaction response. In the examples for 2.0.2 the version 2.0.2 is used. This seems to be a failure in Figure 31.

**Comment by lgoltz** [comment]
We decided to validate against the new schema (2.0.2) independent of the version of the WFS (2.0.0 as well as 2.0.2).
