### ISSUE TITLE
InvalidParameterValue required by "unknownStoredQuery" test

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/ets-wfs20#146]
The `unknownStoredQuery` requires the exception report sent by the WFS server to contain an `InavlidParameterException` code. I scanned the WFS 2.0.0/2.0.2 specification but was not able to find this requirement.

So, an `OperationParsingFailed` or `OperationProcessingFailed` should also be fine?

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigations.

**Comment by VeronikaKusova** [comment]
Hi,
I have similar question regarding **Invoke Get Feature By Id With Unknown Id**. It requires an exception with a status code 404 or 403 (which correspond to an OperationProcessingFailed). But isn’t it the same case as **Unknown stored query**? So, an InvalidParameterValue could be also ok for this test, because there is an invalid value for parameter id in the request.

**Comment by dstenger** [comment]
In case **Invoke Get Feature By Id With Unknown Id** a feature does not exist leading to an exception.
In case **Unknown stored query** a stored query does not exist leading to an exception.

So, **Invoke Get Feature By Id With Unknown Id** sends a parsable request but the request cannot be processed.
Chapter 11.4 of OGC 09-025r1 states:
```
11.4 Exceptions
In the event that a web feature service encounters an error parsing a GetFeature request, it shall raise an
OperationParsingFailed exception as described in 7.5.
In the event that a web feature service encounters an error processing a GetFeature request, it shall raise an
OperationProcessingFailed exception as described in 7.5.
```
Thus, the expected exception is correct.
However, in case of **Unknown stored query** there is a similar setup. Here, you could argue if the service cannot parse or process the request but in both cases an OperationParsingFailed exception is expected.

If you take a look at chapter 7.5 of OGC 09-025r1, there is a helpful example:
```
...
EXAMPLE
If parsing an operation fails because the value of a parameter is invalid, the server should report an
OperationParsingFailed exception and an InvalidParameterValue exception.
...
```
So, in case of **Unknown stored query** an InvalidParameterValue exception should be allowed or even expected as well.

Conclusion:
**Unknown stored query**  shall allow OperationProcessingFailed and InvalidParameterValue exceptions.
In case of **Invoke Get Feature By Id With Unknown Id**, I would say an InvalidParameterValue exception should not be expected because the request can be parsed but just not be processed.

**Comment by dstenger** [comment]
@keshav-nangare Can you please update `Unknown stored query` test to accept OperationProcessingFailed exception as well (in additon to InvalidParameterValue exception)?

**Comment by dstenger** [comment]
@clausnagel Can you provide a test service which is responding with OperationProcessingFailed exception in `Unknown stored query` test?

**Comment by dstenger** [comment]
@VeronikaKusova If you disagree with my conclusion, please open a new issue where we can continue the discussion.

**Comment by dstenger** [comment]
However, if WFS 2.0.2 is used, **Invoke Get Feature By Id With Unknown Id** shall accept NotFound exception as well.
Issue was created: https://github.com/opengeospatial/ets-wfs20/issues/162

**Comment by keshav-nangare** [comment]
@dstenger
