### ISSUE TITLE
BBOXTests#invalidGeometryOperand expects exception

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wfs20#147]
The test org.opengis.cite.iso19142.basic.filter.spatial.BBOXTests#invalidGeometryOperand expects an exception with InvalidParameterValue code and status code 400. 

Test:
https://github.com/opengeospatial/ets-wfs20/blob/35d1d4a865600ceab3fe9df820122e9240cde80d/src/main/java/org/opengis/cite/iso19142/basic/filter/spatial/BBOXTests.java#L197-L224

Some services returns an empty FeatureCollection.

Specification should be rechecked.

**Comment by lgoltz** [comment]
I cannot find any hint in the specification about the correct behavior. 
 * ATS: A.2.22.1.5.2 Invalid property name: "Test Method: Execute a query with an non-existent property name in the projection clause of a query and verify that the server generates an InvalidParameterValue exception."
 * referenced Chapter _11.4: GetFeature - Exceptions_ does not mention the InvalidParameterValue exception
 * referenced Chapter _8.3: Exceptions_ does not exist

I think the test should be removed.

**Comment by dstenger** [comment]
I agree regarding referenced chapter `11.4: GetFeature - Exceptions`.

However, regarding Chapter 8.3 OWS Common (OGC 06-121r3) is referenced. Thus, the chapter exists.
The chapter says following:
```
exceptionCode value: InvalidParameterValue
Meaning of code: Operation request contains an invalid parameter value
“locator” value: Name of parameter with invalid value
```

Nevertheless, in my opinion the link to A.2.22.1.5.2 is not very clear.

**Comment by dstenger** [comment]
@ghobona What do you think of this issue? Shall the test be removed?

**Comment by ghobona** [comment]
We should keep the test.

The standard is clear about the exception to be returned and the response code. Please see Section 7.5, 11.4 and  the attached screenshot from Section D.3.

![Screenshot 2020-09-23 at 10 48 00](https://user-images.githubusercontent.com/18121038/93996632-6630a680-fd8a-11ea-9943-3e1e7143ddf3.png)

**Comment by dstenger** [comment]
Still, it is not clear for me whether this case (see description of issue) should lead to an exception (status code 400) or to an empty feature collection (status code 200).

The specification does not clearly define this special case.

The only abstract test coming close to this test was already referenced in https://github.com/opengeospatial/ets-wfs20/issues/147#issuecomment-529867987. However, it does not clarify the described case.

**Comment by ghobona** [comment]
@cportele May we please have the SWG's view on this issue?

**Comment by cportele** [comment]
It is a general issue with WFS/FES that the requirements are sometimes not clear. But let's have a look at this case:

The test in the original comment references "ISO 19142:2010, 11.4: GetFeature - Exceptions" and "ISO 19143:2010, 8.3: Exceptions".

* The tests should not reference the ISO standards, which are outdated (2.0.0 instead of 2.0.2).
* [Section 8.3 in FES](http://docs.opengeospatial.org/is/09-026r2/09-026r2.html#91) is about exceptions for sorting, so it does not seem applicable.
* [Get Feature - Exceptions](http://docs.opengeospatial.org/is/09-025r2/09-025r2.html#194) is section 11.3 in WFS. Based on the current text I would have excepted an OperationProcessingFailed exception, if there is an exception.
* With respect to the question whether an exception or an empty feature collection should be returned, my reading of FES is that it should be an exception. A [spatial operator as specified by FES (and ISO 19125-1)](http://docs.opengeospatial.org/is/09-026r2/09-026r2.html#55) expects two geometries as operands. If the property is not a geometry (or NULL) then this is invalid input for the operator. The same applies, if a literal is not a geometry literal.

We can discuss this in the SWG meeting today. 

cc @pvretano

**Comment by ghobona** [comment]
@cportele Any further information from the SWG meeting?

**Comment by cportele** [comment]
We discussed it briefly. @pvretano agreed with my general interpretation and we decided that he will add another comment to this issue.

**Comment by pvretano** [comment]
@ghobona  at its core the test is for a invalid Geometry operand and so if the operand does not resolve to a valid geometry (i.e. a property with a geometric value or a geometry literal) then an exception should be thrown as specified in the spec.  So, @cportele's explanation is correct.

**Comment by dstenger** [comment]
Thank you for your expertise.

@ghobona Thus, I propose to leave the test as it is and to also allow OperationProcessingFailed (Status Code 403) as valid exception type.

**Comment by ghobona** [comment]
@dstenger Agreed.
