### ISSUE TITLE
Unexpected error messages on nil and descendant elements

### ISSUE THREAD

**Issue by JohannaOtt** [opengeospatial/ets-wfs20#206]
When validating [this WFS](https://haleconnect.com/ows/services/org.292.6cef2128-a227-4aa7-bc74-0e3797644d51_wfs?SERVICE=WFS&REQUEST=GetCapabilities&VERSION=2.0.0) I get two errors concerning CEMTClass that I cannot understand when looking at the data:

    Test ID EID5c4808a6-566d-3b93-a5e5-e6002f4fc8a7 returns: Unexpected result evaluating XPath expression with context node tn-w:CEMTClass:
    ns1:validFrom[@xsi:nil='true'] expected [true] but found [false]

    Test ID EID6d46ac1b-5490-3b3f-a19a-1487ae31dc22 returns: Unexpected number of {http://inspire.ec.europa.eu/schemas/tn-w/4.0}CEMTClass descendant elements. expected [2] but found [4]

This is an excerpt of the data with all CEMTClass objects contained
CEMTClass.zip

This is a follow up ticket from https://github.com/INSPIRE-MIF/helpdesk-validator/issues/620

**Comment by dstenger** [comment]
Following request is sent by the test:
* POST https://haleconnect.com/ows/services/org.292.6cef2128-a227-4aa7-bc74-0e3797644d51_wfs
* Body:
```
<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs/2.0" count="10" service="WFS"
                version="2.0.0">
   <wfs:Query xmlns:ns79="http://inspire.ec.europa.eu/schemas/tn-w/4.0"
              typeNames="ns79:CEMTClass">
      <Filter xmlns="http://www.opengis.net/fes/2.0">
         <ResourceId rid="INSPIRE.CEMTClass.V_A"/>
         <ResourceId rid="INSPIRE.CEMTClass.I"/>
      </Filter>
   </wfs:Query>
</wfs:GetFeature>
```

The test expects two elements of `tn-w:CEMTClass`.
However, four are present because both returned features (these are the two expected) contain an element `tn-w:CEMTClass` which is exactly the same as the feature itself. These are the two other matches.

When checking the schema (https://inspire.ec.europa.eu/schemas/tn-w/4.0/WaterTransportNetwork.xsd), following can be found:
```
...
  <element name="CEMTClass" substitutionGroup="tn:TransportProperty" type="tn-w:CEMTClassType">
...
          <element name="CEMTClass" type="tn-w:CEMTClassValueType">
...
```

Thus, it seems that the four elements are valid and the test suite has to be more precise to prevent this case.
I propose to update the test suite to just consider child elements of `wfs:member`.

**Comment by JohannaOtt** [comment]
@dstenger I saw that you closed this issue. How often is the OGC Team validator released? So when can I expect the behavior to change in the OGC and therefore the INSPIRE Validator?

**Comment by dstenger** [comment]
We are planning to create a new Beta release (https://cite.opengeospatial.org/te2/) next month.
Production is just updated every 6 months. We do not have an exact date for the next update, yet. However, it will be most likely in next spring.
Regarding the INSPIRE Validator I can unfortunately not provide any information as I am not involved in that project.

**Comment by JohannaOtt** [comment]
> We are planning to create a new Beta release (https://cite.opengeospatial.org/te2/) next month.

@dstenger Did this happen? If yes, the fix did not help. I am still running into the errors described above on the Beta system: 
![grafik](https://user-images.githubusercontent.com/34163838/148176864-0ef6dd77-37da-454b-b95f-e491026ac605.png)

**Comment by dstenger** [comment]
Unfortunately, the release was postponed because we are still working on some further WFS 2.0 issues which will also be part of the deployment.
So, we scheduled the release for end of this month.

One additional hint, https://cite.opengeospatial.org/te2/ displays the currently installed version of the test suite (`Web Feature Service (WFS) | 2.0 | 1.36 | Final`). As soon as `1.37` (see value in milestone of this issue) will be displayed there, the fix will be available on that environment.

**Comment by JohannaOtt** [comment]
@dstenger Ok great, thanks for the feedback and the version hint.

**Comment by JohannaOtt** [comment]
Good news: The "Unexpected number" errors do not occur any longer.
But he "Unexpected result" errors are still there afer the deployment 
![grafik](https://user-images.githubusercontent.com/34163838/152553820-a42a24d3-cc54-4bf0-9897-4b01425f15d8.png)

@dstenger Don't you consider them being part of this issue?

**Comment by dstenger** [comment]
Thank you for the feedback!
Unfortunately, the fix is just fixing the failure regarding test `Two Valid Feature Identifiers`.
Can you please open a new issue for the other test?

**Comment by JohannaOtt** [comment]
@dstenger I created https://github.com/opengeospatial/ets-wfs20/issues/223 for it
