### ISSUE TITLE
Migrate test suite to TEAM Engine 6 (Java 17)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#266]
Currently, there is just a SNAPSHOT of TEAM Engine 6.0.

First work was already done here: https://github.com/opengeospatial/teamengine/issues/606

Error message is:
```
Error in call to extension function {public java.lang.Object com.occamlab.te.TECore.callFunction(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo) throws java.lang.Exception}: Exception in extension function net.sf.saxon.s9api.SaxonApiException: Error in call to extension function {public javax.xml.transform.Source org.opengis.cite.iso19142.TestNGController.doTestRun(org.w3c.dom.Document) throws java.lang.Exception}: Exception in extension function java.lang.ExceptionInInitializerError
```

**Comment by bpross-52n** [comment]
There is a version 5.0 planned for the https://github.com/Geomatys/geotoolkit. This version could be used in the WFS 2.0 test suite, the GML 32 test suite, as well as the geomatics-geotk project.

**Comment by bpross-52n** [comment]
@desruisseaux Can you tell us, when the release of Geotoolkit 5.0 is planned?

**Comment by dstenger** [comment]
Working branch is https://github.com/opengeospatial/ets-wfs20/tree/java17Tomcat101TeamEngine6

**Comment by desruisseaux** [comment]
Hello @bpross-52n . Sorry, I didn't saw this message before.

We publish milestones of Geotk every few months on [this repository](https://nexus.geomatys.com/service/rest/repository/browse/maven-public/org/geotoolkit/geotoolkit/). The last milestone was last September and is already on Java 17. However, we don't make publicity about those milestones because they depend on a non-released version of the OGC GeoAPI standard. The official releases are Apache SIS, which depend on the released OGC GeoAPI 3.0.2 standard, but that project does not yet have all you need. However, as discussed with Gobe and Dick, the fact that Geotk depends on a non-released GeoAPI version may be acceptable for TEAM engine purpose because I think that this standard is not exposed to TEAM users.

I will work on migrating the https://github.com/opengeospatial/geomatics-geotk repository during this OGC / OSGeo / ASF code sprint and keep you informed.

**Comment by desruisseaux** [comment]
Initial migration done on the `sis-migration` branch of https://github.com/Geomatys/geomatics-geotk. There is two tests failure to fix.

**Comment by desruisseaux** [comment]
Pull request for the first dependency: https://github.com/opengeospatial/geomatics-geotk/pull/15
