### ISSUE TITLE
Test deletedFeatureIsRetired (Feature versions) requests wrong version of feature

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wfs20#51]
We detected a bug in test deletedFeatureIsRetired.
The test deletedFeatureIsRetired requests the last version of a feature after having deleted it. The parameter version="LAST" is used for that.

The problem is that the test does not request the last version as version="LAST" is set after the request has already been sent.

Line 243 - 245 of VersioningTests [1] are relevant:

```
        ResourceId qryId = new ResourceId(gmlId);
        rsp = this.wfsClient.GetFeatureVersion(qryId, typeName);
        qryId.setVersion(FES2.VersionAction.LAST.name());
```

[1] org.opengis.cite.iso19142.versioning.VersioningTests

**Comment by rjmartell** [comment]
There are two steps in this test:

1. Submit a transaction request to delete a feature instance; the response must report totalDeleted=1 (and the server updates its status)
2. Submit a query to retrieve the LAST version in the version chain

The second request is filtering the version chain, the last member of which should be "retired" because the feature was previously deleted. The version chain should look like this in the simplest case:

```
r1 [FIRST; status: superseded] ---> r2 [LAST; status: retired]
```

**Comment by lgoltz** [comment]
We totally agree with the test steps. But the point is, that the second request does not contain the VersionAction "LAST" as it is  set after the request is submitted. Swapping lines 244 and 245 in https://github.com/opengeospatial/ets-wfs20/blob/1.25/src/main/java/org/opengis/cite/iso19142/versioning/VersioningTests.java should do it.
